spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
  application:
    name: kanji-master
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kanji-master}
    username: ${DB_USER:kanji-master}
    password: ${DB_PASSWORD:kanji-master}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  graphql:
    graphiql:
      enabled: true

  main:
    allow-circular-references: true

server:
  port : ${PORT:8080}

openai:
  model: 'gpt-4o-mini'
  api:
    url: 'https://api.openai.com/v1/chat/completions'
    key: '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'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


