spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
  application:
    name: kanji-master
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kanji-master}
    username: ${DB_USER:kanji-master}
    password: ${DB_PASSWORD:kanji-master}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  graphql:
    graphiql:
      enabled: true

  main:
    allow-circular-references: true
#  flyway:
#    baselineOnMigrate: true
#    validateOnMigrate: false
#    locations: classpath:db/migration
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kanji-master}
#    user: kanji-master
#    password: kanji-master
#    schemas: kanji-master


server:
  port : ${PORT:8080}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


