drop table if exists radical cascade;
create table radical
(
    radical text    not null
        primary key,
    radvar  text,
    number  integer not null,
    strokes integer not null,
    names   text    not null,
    meaning text    not null,
    notes   text
);

insert into radical (radical, radvar, number, strokes, names, meaning, notes)
values  ('一', null, 1, 1, 'いち', 'one', null),
        ('丨', null, 2, 1, 'ぼう・たてぼう', 'line', null),
        ('丶', null, 3, 1, 'てん・ちょぼ・ちゅ・ちゅてん', 'dot', null),
        ('丿', null, 4, 1, 'の・のかんむり・はらいぼう', 'slash', null),
        ('乙', '乚', 5, 1, 'おつ・おつにょう・つりばり', 'second', 'Also ⺄.'),
        ('亅', null, 6, 1, 'はねぼう', 'hook', null),
        ('二', null, 7, 2, 'に', 'two', null),
        ('亠', null, 8, 2, 'けいさん・けいさんかんむり・なべぶた', 'lid', null),
        ('人', '亻', 9, 2, 'ひと・にんべん・ひとやね・ひとかんむり・ひとがしら', 'man, human', 'Also 𠆢 when at top (ひとやね, ひとかんむり or ひとがしら).'),
        ('儿', null, 10, 2, 'にんにょう・ひとあし', 'legs', null),
        ('入', null, 11, 2, 'いる・にゅう・いりがしら・いりやね', 'enter', null),
        ('八', null, 12, 2, 'はち・は・はちがしら', 'eight', null),
        ('冂', null, 13, 2, 'けいがまえ・まきがまえ・どうがまえ・えんがまえ', 'open country', null),
        ('冖', null, 14, 2, 'わかんむり', 'cover', null),
        ('冫', null, 15, 2, 'にすい', 'ice', null),
        ('几', '𠘨', 16, 2, 'つくえ・きにょう・つくえきにょう・かぜかんむり・かぜがまえ・かざがまえ', 'table', null),
        ('凵', null, 17, 2, 'かんにょう・うけばこ・かんがまえ', 'container, open mouth', null),
        ('刀', '刂', 18, 2, 'かたな・りっとう', 'knife, sword', null),
        ('力', null, 19, 2, 'ちから・りきづくり', 'power, force', null),
        ('勹', null, 20, 2, 'つつみがまえ・くがまえ', 'wrap, embrace', null),
        ('匕', null, 21, 2, 'さじ・さじのひ・さじづくり・ひ', 'spoon', null),
        ('匚', null, 22, 2, 'はこ・はこがまえ', 'box', null),
        ('匸', null, 23, 2, 'かくしがまえ', 'hiding enclosure', null),
        ('十', null, 24, 2, 'じゅう・じゅうへん', 'ten, complete', null),
        ('卜', null, 25, 2, 'ぼく・ぼくづくり・ぼくのと・と・うらない', 'divination', null),
        ('卩', '㔾', 26, 2, 'ふし・ふしづくり・わりふ', 'kneel', null),
        ('厂', null, 27, 2, 'がんだれ', 'cliff', null),
        ('厶', null, 28, 2, 'む', 'private', null),
        ('又', null, 29, 2, 'また', 'right hand', null),
        ('口', null, 30, 3, 'くち・くちへん', 'mouth, opening', null),
        ('囗', null, 31, 3, 'くに・くにがまえ', 'enclosure', null),
        ('土', null, 32, 3, 'つち・つちへん・どへん', 'earth', null),
        ('士', null, 33, 3, 'さむらい', 'scholar, bachelor', null),
        ('夂', null, 34, 3, 'ちかんむり・ふゆがしら', 'go slowly, winter', null),
        ('夊', null, 35, 3, 'なつあし・すいにょう', 'go slowly', null),
        ('夕', null, 36, 3, 'ゆう・ゆうべ・た', 'evening, sunset', null),
        ('大', null, 37, 3, 'だい・おおきい', 'big, very', null),
        ('女', null, 38, 3, 'おんな・おんなへん', 'woman, female', null),
        ('子', null, 39, 3, 'こ・こへん', 'child, seed', null),
        ('宀', null, 40, 3, 'うかんむり', 'roof', null),
        ('寸', null, 41, 3, 'すん・すんづくり', 'thumb, inch', null),
        ('小', '⺌', 42, 3, 'しょう・ちいさい・なおがしら・つ', 'small, insignificant', 'Also ⺍ (called つ because it looks like katakana ツ).'),
        ('尢', '尣', 43, 3, 'まげあし・だいのまげあし・あう・おうにょう', 'lame', null),
        ('尸', null, 44, 3, 'しかばね・かばね・かばねだれ', 'corpse', null),
        ('屮', null, 45, 3, 'くさのめ・めばえ・てつ', 'sprout', null),
        ('山', null, 46, 3, 'やま・やまへん・やまかんむり', 'mountain', null),
        ('巛', '川', 47, 3, 'かわ・まがりがわ・さんぼんがわ', 'river', 'Also 巜.'),
        ('工', null, 48, 3, 'こう・たくみ・たくみへん・え', 'work', null),
        ('己', '巳', 49, 3, 'おのれ・き・つちのと', 'oneself', null),
        ('巾', null, 50, 3, 'はば・はばへん・きんべん', 'turban, scarf', null),
        ('干', null, 51, 3, 'かん・いちじゅう・ほす・ひる・たてかん', 'pestle', null),
        ('幺', null, 52, 3, 'いとがしら・よう', 'short, tiny', null),
        ('广', null, 53, 3, 'まだれ', 'house on cliff', null),
        ('廴', null, 54, 3, 'えんにょう・いんにょう', 'long stride', null),
        ('廾', null, 55, 3, 'にじゅう・にじゅうあし・こまぬき', 'two hands, twenty', null),
        ('弋', null, 56, 3, 'しきがまえ・いぐるみ', 'shoot, arrow', null),
        ('弓', null, 57, 3, 'ゆみ・ゆみへん', 'bow', null),
        ('彑', '彐', 58, 3, 'けい・けいがしら・いのこがしら', 'pig snout', null),
        ('彡', null, 59, 3, 'さん・さんづくり', 'bristle, beard', null),
        ('彳', null, 60, 3, 'ぎょうにんべん', 'step', null),
        ('心', '忄', 61, 4, 'こころ・したごころ・りっしんべん', 'heart', 'Also 㣺 when at bottom (したごころ).'),
        ('戈', null, 62, 4, 'ほこ・ほこづくり・ほこがまえ・かのほこ', 'spear, halberd', null),
        ('戶', '戸', 63, 4, 'と・とだれ・とかんむり', 'door, house', 'Simplified Chinese: 户.'),
        ('手', '扌', 64, 4, 'て・てへん', 'hand', null),
        ('支', null, 65, 4, 'し・しにょう・えだにょう・じゅうまた', 'branch', null),
        ('攴', '攵', 66, 4, 'ぼくにょう・ぼくづくり・とまた・のぶん・しぶん', 'rap', null),
        ('文', null, 67, 4, 'ぶん・ぶんにょう', 'script, literature', null),
        ('斗', null, 68, 4, 'と・とます・ますづくり', 'dipper', null),
        ('斤', null, 69, 4, 'おの・おのづくり・きん', 'axe', null),
        ('方', null, 70, 4, 'ほう・ほうへん・かた・かたへん', 'square', null),
        ('无', '旡', 71, 4, 'む・むにょう・すでのつくり', 'perish', 'Always uses its variant form as a component in other kanji and has 5 strokes in Jōyō and Jinmeiyō kanji (and in 漑), and 4 as a component in other kanji.'),
        ('日', null, 72, 4, 'ひ・ひへん・にち・にちへん', 'sun, day', null),
        ('曰', null, 73, 4, 'ひらび・いわく', 'say', null),
        ('月', null, 74, 4, 'つき・つきへん', 'moon, month', null),
        ('木', null, 75, 4, 'き・きへん', 'tree', null),
        ('欠', null, 76, 4, 'あくび・けんづくり・かける・けつ', 'lack, yawn', null),
        ('止', null, 77, 4, 'とまる・とめる・とめへん', 'stop', null),
        ('歹', '歺', 78, 4, 'がつ・がってん・がつへん・かばね・かばねへん・いちたへん', 'death, decay', null),
        ('殳', null, 79, 4, 'るまた・ほこづくり', 'weapon, lance', null),
        ('毋', '母', 80, 4, 'なし・なかれ・はは・ははのかん', 'mother, do not', null),
        ('比', null, 81, 4, 'ひ・くらべる・ならびひ', 'compare, compete', null),
        ('毛', null, 82, 4, 'け', 'fur, hair', null),
        ('氏', null, 83, 4, 'うじ', 'clan', null),
        ('气', null, 84, 4, 'きがまえ', 'steam, breath', null),
        ('水', '氵', 85, 4, 'みず・したみず・さんずい', 'water', 'Also 氺 when at bottom (したみず).'),
        ('火', '灬', 86, 4, 'ひ・ひへん・れっか・れんが', 'fire', null),
        ('爪', '爫', 87, 4, 'つめ・つめがしら・つめかんむり・そうにょう・のつ', 'claw', 'Also 爫.'),
        ('父', null, 88, 4, 'ちち', 'father', null),
        ('爻', null, 89, 4, 'こう・めめ', 'mix, twine, cross', null),
        ('爿', '丬', 90, 4, 'しょうへん', 'split wood', null),
        ('片', null, 91, 4, 'かた・かたへん', 'slice', null),
        ('牙', null, 92, 4, 'きば・きばへん', 'fang', 'Has 4 strokes as itself, 5 as a component in Jōyō kanji (and in 冴), and 4 as a component in other kanji.'),
        ('牛', '牜', 93, 4, 'うし・うしへん', 'cow', 'Also ⺧.'),
        ('犬', '犭', 94, 4, 'いぬ・けものへん', 'dog', null),
        ('玄', null, 95, 4, 'げん', 'dark, profound', null),
        ('玉', '王', 96, 4, 'たま・たまへん・おう・おうへん・あうさま', 'jade, king', 'Also ⺩ (たまへん).'),
        ('瓜', null, 97, 5, 'うり', 'melon', null),
        ('瓦', null, 98, 5, 'かわら', 'tile', null),
        ('甘', null, 99, 5, 'あまい・かん', 'sweet', null),
        ('生', null, 100, 5, 'うむ・うまれる・いきる', 'life', null),
        ('用', null, 101, 5, 'もちいる・よう', 'use', null),
        ('田', null, 102, 5, 'た・たへん', 'field', null),
        ('疋', '𤴔', 103, 5, 'ひき・ひきへん', 'bolt of cloth', null),
        ('疒', null, 104, 5, 'やまい・やまいだれ', 'sickness', null),
        ('癶', null, 105, 5, 'はつがしら', 'footsteps', null),
        ('白', null, 106, 5, 'しろ・しろへん', 'white', null),
        ('皮', null, 107, 5, 'かわ・けがわ・ひのかわ', 'skin', null),
        ('皿', null, 108, 5, 'さら', 'dish', null),
        ('目', null, 109, 5, 'め・めへん・よこめ', 'eye', null),
        ('矛', null, 110, 5, 'ほこ・ほこへん・むのほこ', 'spear', null),
        ('矢', null, 111, 5, 'や・やへん', 'arrow', null),
        ('石', null, 112, 5, 'いし・いしへん', 'stone', null),
        ('示', '礻', 113, 5, 'しめす・しめすへん', 'sign', 'Also ⺬.'),
        ('禸', null, 114, 5, 'あしあと・ぐうのあし', 'track', null),
        ('禾', null, 115, 5, 'のぎ・のぎへん', 'grain', null),
        ('穴', null, 116, 5, 'あな・あなかんむり', 'cave', null),
        ('立', null, 117, 5, 'たつ・たつへん', 'stand, erect', null),
        ('竹', '⺮', 118, 6, 'たけ・たけかんむり', 'bamboo', null),
        ('米', null, 119, 6, 'こめ・こめへん', 'rice', null),
        ('糸', '糹', 120, 6, 'いと・いとへん', 'silk', 'Simplified Chinese: 纟.'),
        ('缶', null, 121, 6, 'ほとぎ・ほとぎへん', 'jar', null),
        ('网', '罒', 122, 6, 'あみ・あみがしら・あみめ・よこめ・よんかしら', 'net', null),
        ('羊', '𦍌', 123, 6, 'ひつじ・ひつじへん・ひつじかんむり', 'sheep', 'Also ⺶ (ひつじへん).'),
        ('羽', '羽', 124, 6, 'はね', 'feather', null),
        ('老', '耂', 125, 6, 'おい・おいかんむり・おいがしら', 'old', null),
        ('而', null, 126, 6, 'しかし・しかして・しこうして', 'beard', null),
        ('耒', null, 127, 6, 'すき・すきへん・らいすき・らいへん', 'plow', null),
        ('耳', null, 128, 6, 'みみ・みみへん', 'ear', null),
        ('聿', '⺺', 129, 6, 'ふで・ふでづくり・ふでがしら', 'brush', 'Also ⺻ (ふでがしら).'),
        ('肉', '⺼', 130, 6, 'にく・にくづき', 'meat', null),
        ('臣', null, 131, 7, 'しん・おみ', 'minster, official', null),
        ('自', null, 132, 6, 'みずから', 'self', null),
        ('至', null, 133, 6, 'いたる', 'arrive', null),
        ('臼', null, 134, 6, 'うす', 'mortar', null),
        ('舌', null, 135, 6, 'した・したへん', 'tongue', null),
        ('舛', null, 136, 6, 'ます・まいあし', 'opposite', 'Has 6 strokes as itself, 7 as a component in Jōyō and Jinmeiyō kanji and 6 as a component in other kanji.'),
        ('舟', null, 137, 6, 'ふね・ふねへん', 'boat', null),
        ('艮', null, 138, 6, 'うしとら・こん・こんづくり・ねづくり', 'stopping', null),
        ('色', null, 139, 6, 'いろ', 'colour, prettiness', null),
        ('艸', '艹', 140, 6, 'くさ・くさかんむり', 'grass', 'Also 䒑 and rarely 艹 and 艹.'),
        ('虍', '虎', 141, 6, 'とら・とらがしら・とらかんむり', 'tiger, tiger stripes', 'とらだれ would be more accurate.'),
        ('虫', null, 142, 6, 'むし・むしへん', 'insect', null),
        ('血', null, 143, 6, 'ち・ちへん', 'blood', null),
        ('行', null, 144, 6, 'ぎょう・ぎょうがまえ・いく・ゆきがまえ', 'go, do', null),
        ('衣', '衤', 145, 6, 'ころも・ころもへん', 'clothes', null),
        ('西', '覀', 146, 6, 'にし・かなめのかしら・おおいかんむり', 'west', 'Also 襾.'),
        ('見', null, 147, 7, 'みる', 'see', null),
        ('角', null, 148, 7, 'つの・かく・つのへん', 'horn', null),
        ('言', '訁', 149, 7, 'いう・げん・ごんべん・ことば', 'speech', 'Simplified Chinese: 讠.'),
        ('谷', null, 150, 7, 'たに・たにへん', 'valley', null),
        ('豆', null, 151, 7, 'まめ・まめへん', 'bean', null),
        ('豕', null, 152, 7, 'いのこ・いのこへん・ぶた', 'pig', null),
        ('豸', null, 153, 7, 'むじな・むじなへん', 'cat, badger', null),
        ('貝', null, 154, 7, 'かい・かいへん・こがい', 'shell', 'Simplified Chinese: 贝.'),
        ('赤', null, 155, 7, 'あか・あかへん', 'red, naked', null),
        ('走', null, 156, 7, 'はしる・そうにょう', 'run', null),
        ('足', '𧾷', 157, 7, 'あし・あしへん', 'foot', null),
        ('身', null, 158, 7, 'み・みへん', 'body', null),
        ('車', null, 159, 7, 'くるま・くるまへん', 'cart, car', 'Simplified Chinese: 车.'),
        ('辛', null, 160, 7, 'しん・からい', 'bitter', null),
        ('辰', null, 161, 7, 'たつ・しんのたつ', 'morning', null),
        ('辵', '辶', 162, 3, 'しんにょう・しんにゅう', 'walk', 'The old form is 辶.'),
        ('邑', '⻏', 163, 7, 'おおざと・おおざとづくり・ゆう', 'town', null),
        ('酉', null, 164, 7, 'とり・とりへん・ひよみのとり・さけのとり', 'wine, alcohol', null),
        ('釆', null, 165, 7, 'のごめ・のごめへん', 'divide, distinguish, choose', null),
        ('里', null, 166, 7, 'さと・さとへん', 'village, mile', null),
        ('金', '釒', 167, 8, 'かね・かねへん', 'metal, gold', 'Simplified Chinese: 钅.'),
        ('長', '镸', 168, 8, 'ながい', 'long, grow', 'Simplified Chinese: 长.'),
        ('門', null, 169, 8, 'もん・もんがまえ・かどがまえ', 'gate', 'Simplified Chinese: 门.'),
        ('阜', '⻖', 170, 8, 'こざと・こざとへん・おか・ぎふのふ', 'mound, dam', null),
        ('隶', null, 171, 8, 'たい・たいづくり・れいづくり・れいのつくり', 'slave, capture', null),
        ('隹', null, 172, 8, 'ふるとり', 'small bird', null),
        ('雨', '⻗', 173, 8, 'あめ・あめかんむり・あまかんむり', 'rain', null),
        ('青', '靑', 174, 8, 'あお・あおへん', 'blue', null),
        ('非', null, 175, 8, 'あらず', 'wrong', null),
        ('面', null, 176, 9, 'めん', 'face', null),
        ('革', null, 177, 9, 'かわ・かくのかわ・かわへん・つくりがわ', 'leather, rawhide', null),
        ('韋', null, 178, 10, 'なめしがわ', 'tanned leather', 'Simplified Chinese: 韦.'),
        ('韭', null, 179, 9, 'にら', 'leek', null),
        ('音', null, 180, 9, 'おと', 'sound', null),
        ('頁', null, 181, 9, 'おおがい・いちのかい', 'leaf', 'Simplified Chinese: 页.'),
        ('風', null, 182, 9, 'かぜ', 'wind', 'Simplified Chinese: 风.'),
        ('飛', null, 183, 9, 'とぶ', 'fly', 'Simplified Chinese: 飞.'),
        ('食', '飠', 184, 9, 'しょく・しょくへん', 'eat, food', 'Also 𩙿. Simplified Chinese: 饣.'),
        ('首', null, 185, 9, 'くび', 'head', null),
        ('香', null, 186, 9, 'か・こう・かおり・においこう', 'fragrance', null),
        ('馬', null, 187, 10, 'うま・うまへん', 'horse', 'Simplified Chinese: 马.'),
        ('骨', null, 188, 10, 'ほね・ほねへん', 'bone', null),
        ('高', null, 189, 10, 'たかい', 'tall', null),
        ('髟', null, 190, 10, 'かみがしら・かみかんむり', 'long hair', null),
        ('鬥', null, 191, 10, 'たたかいがまえ・とうがまえ', 'fight', null),
        ('鬯', null, 192, 10, 'ちょう・においざけ・かおりぐさ', 'herbs, sacrificial wine', null),
        ('鬲', null, 193, 10, 'れき・れきのかなえ', 'tripod, cauldron', null),
        ('鬼', null, 194, 10, 'おに・きにょう', 'ghost, demon', null),
        ('魚', null, 195, 11, 'うお・うおへん・さかな', 'fish', 'Simplified Chinese: 鱼.'),
        ('鳥', null, 196, 11, 'とり・とりへん', 'bird', 'Simplified Chinese: 鸟.'),
        ('鹵', null, 197, 11, 'ろ・しお・しおへん', 'salt', null),
        ('鹿', null, 198, 11, 'しか・しかへん', 'deer', null),
        ('麥', '麦', 199, 11, 'むぎ・ぼく・ばくにょう', 'wheat', null),
        ('麻', null, 200, 11, 'あさ・あさかんむり', 'hemp, flax', 'あさだれ would be more accurate.'),
        ('黄', '黃', 201, 11, 'き・きいろ', 'yellow', null),
        ('黍', null, 202, 12, 'きび', 'millet', null),
        ('黑', '黒', 203, 12, 'くろ・くろい・くろへん', 'black', null),
        ('黹', null, 204, 12, 'ち・ぬいとり・ふつ・ふつへん', 'embroidery, needlework', null),
        ('黽', null, 205, 13, 'おおがえる・べん・ぼう・ひきがえる', 'frog, amphibian', 'Simplified Chinese: 黾.'),
        ('鼎', null, 206, 13, 'かなえ・てい', 'tripod', null),
        ('鼓', null, 207, 13, 'つづみ', 'drum', null),
        ('鼠', null, 208, 13, 'ねずみ・ねずみへん', 'rat, mouse', null),
        ('鼻', null, 209, 14, 'はな・はなへん', 'nose', null),
        ('齊', '斉', 210, 14, 'さい・せい・ととのえる', 'even, uniformly', 'Simplified Chinese: 齐.'),
        ('齒', '歯', 211, 15, 'は・はへん', 'tooth, molar', 'Simplified Chinese: 齿.'),
        ('龍', '竜', 212, 16, 'りゅう・たつ', 'dragon', 'Simplified Chinese: 龙.'),
        ('龜', '亀', 213, 16, 'かめ', 'turtle, tortoise', 'Simplified Chinese: 龟.'),
        ('龠', null, 214, 17, 'やく・やくのふえ', 'flute', null);